testing restore container: test with teeth added

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -274,14 +274,28 @@ jobs:
           name: Verify Azure RESTORE succeeded to single instance
           command: |
               NAMESPACE=ns-$CIRCLE_BUILD_NUM
-              export NEO4J_PASSWORD=mySecretPassword
+              export NEO4J_PASSWORD=mySecretPassword              
               kubectl logs --namespace $NAMESPACE $NAME_RESTORE-neo4j-core-0 \
                 -c restore-from-backup | tee -a $BUILD_ARTIFACTS/restore.log
-              echo "MATCH (n) RETURN count(n);" | kubectl run -i --rm cypher-shell \
+
+              # Wait for instance to come alive.
+              kubectl rollout status --namespace $NAMESPACE StatefulSet/$NAME_RESTORE-neo4j-core --watch | tee -a $BUILD_ARTIFACTS/wait-standalone-restore.txt
+
+              result=$(echo "MATCH (n) RETURN count(n);" | kubectl run -i --rm cypher-shell \
                 --namespace $NAMESPACE \
                 --image=neo4j:4.1.3-enterprise --restart=Never \
                 --command -- ./bin/cypher-shell -u neo4j -p "$NEO4J_PASSWORD" \
-                -a neo4j://$NAME_RESTORE-neo4j.default.svc.cluster.local
+                -a neo4j://$NAME_RESTORE-neo4j.default.svc.cluster.local 2>&1)
+              echo $result | tee -a $BUILD_ARTIFACTS/restore.log
+
+              # Strip all cypher shell output down to a single integer result cound for n
+              record_count=$(echo $result | sed 's|^.*n ||' | sed 's| .*$||')
+              if [ $record_count -gt 1000 ] ; then 
+                echo "Test pass" ; 
+              else 
+                echo "Test FAIL with record count $record_count"
+                exit 1
+              fi
 
       - run:
           name: Uninstall / Cleanup
